export const environment = {
  production: true,
  baseUrlSupaBase: 'https://abxvxsfcdgwzmzpqkeus.supabase.co/rest/v1/',
  supaBaseApiKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFieHZ4c2ZjZGd3em16cHFrZXVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjQ2MzIyODcsImV4cCI6MTk4MDIwODI4N30.KWXKJUEvkcrG0Q4_Zd_s-Z_qxQSgplQGPe-GJmQJzsU',
  supaBaseAuth: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFieHZ4c2ZjZGd3em16cHFrZXVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjQ2MzIyODcsImV4cCI6MTk4MDIwODI4N30.KWXKJUEvkcrG0Q4_Zd_s-Z_qxQSgplQGPe-GJmQJzsU'
};
